project:
  type: default
  output-dir: ../docs/notebooks/html
  render:
    - "*.qmd"

execute:
  freeze: auto
  jupyter: uncertainty-flow

format:
  html:
    self-contained: true
    embed-resources: true
    code-fold: true
    code-tools: true
    theme: cosmo
